[package]
name = "kernel-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32"
bitcoinkernel = "0.2.0"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
rawtx-rs = { git = "https://github.com/0xB10C/rawtx-rs", branch = "master" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.21"
tx-indexer-fingerprints = { git = "https://github.com/payjoin/tx-indexer", branch = "master" }
polars = { version = "0.51", default-features = false, features = ["parquet"] }
rayon = "1.12"
